story4/story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

story4/website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.home, name='home'),
    path('gallery/', views.gallery, name='gallery'),
]

story4/website/models.py
from django.db import models

# Create your models here.

story4/website/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'index.html')

def gallery(request):
    return render(request, 'gallery.html')

story4/website/templates/gallery.html
{% extends 'navigation.html' %}
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Random</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
    {% block content %}
    <!-- gallery -->
    <h1 id="random-gallery">just a random gallery.<hr></h1>
    <div class="container">
        <div class="gal row">
            <img class="col-lg-3 col-md-3 col-sm-4 col-4" src="{% static 'images/1.jpg' %}" alt="photo">
            <img class="col-lg-3 col-md-3 col-sm-4 col-4" src="{% static 'images/2.jpg' %}" alt="photo">
            <img class="col-lg-3 col-md-3 col-sm-4 col-4" src="{% static 'images/3.jpg' %}" alt="photo">
            <img class="col-lg-3 col-md-3 col-sm-4 col-4" src="{% static 'images/4.jpg' %}" alt="photo">
            <img class="col-lg-3 col-md-3 col-sm-4 col-4" src="{% static 'images/5.jpg' %}" alt="photo">
            <img class="col-lg-3 col-md-3 col-sm-4 col-4" src="{% static 'images/6.jpg' %}" alt="photo">
            <img class="col-lg-3 col-md-3 col-sm-4 col-4" src="{% static 'images/7.jpg' %}" alt="photo">
            <img class="col-lg-3 col-md-3 col-sm-4 col-4" src="{% static 'images/8.jpg' %}" alt="photo">
            <img class="col-lg-3 col-md-3 col-sm-4 col-4" src="{% static 'images/9.jpg' %}" alt="photo">
            <img class="col-lg-3 col-md-3 col-sm-4 col-4" src="{% static 'images/10.jpg' %}" alt="photo">
            <img class="col-lg-3 col-md-3 col-sm-4 col-4" src="{% static 'images/11.jpg' %}" alt="photo">
            <img class="col-lg-3 col-md-3 col-sm-4 col-4" src="{% static 'images/12.jpg' %}" alt="photo">
        </div>
    </div>
    {% endblock %}
    
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

story4/website/templates/index.html
{% extends 'navigation.html' %}
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Andin</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
	{% block content %}
	<!-- home -->
	<div class="container-fluid" id="home">
		<h1 id="hello">HELLO<span style="color:#fff">!</span></h1>
		<hr id="home-line">
		<p class="intro"><br>I’m <mark style="color: #FF5757">Nabila Rizkiandini</mark>,
			<br>
			a <span style="color:#fff">Computer Science</span> undergraduate student
			<br>
			majoring in <span style="color:#fff">Information System</span>.</p>
	</div>

	<!-- about -->
	<div class="container" id="about">
		<img class="rounded mx-auto d-block" id="photo" src="{% static 'images/photo.png' %}" alt="photo">
		<div class="row">
			<div class="about-me col" style="color: #FF5757">
				about <span style="color:#fff">me</span>.
			</div>
			<div class="card content col-lg-8 col-sm-12 mx-auto justify-content-center" style="background: #FF5757">
				<p id="desc">I’m a second year undergraduate student<br>
					who recently have an interest in design.<br>
					I like to explore many things<br>
					and still have much to achieve.</p>
			</div>
			<div class="more col align-self-center">
				<a class="click" href="#education"><p style="color:#FF5757">i want <span style="color:#fff">to</span>
					<br><span style="color:#fff">hear</span> more</p></a>
			</div>
		</div> 
	</div>

	<!-- education -->
	<div class="container-fluid" id="education">
		<div class="row">
			<div class="card education col-8">
				<hr id="ed-line">
				<div class="ed-year">
					<h1 class="year">2018 - Present</h1>
				</div>
				<h1 class="school" style="font-weight: bold">University of Indonesia</h1>
				<h5 class="fac">Faculty of Computer Science</h5>
				<div class="ed-year">
					<h1 class="year">2015 - 2018</h1>
				</div>
				<h1 class="school">SMAN 2 Bekasi</h1>
				<div class="ed-year">
					<h1 class="year">2012 - 2015</h1>
				</div>
				<h1 class="school">SMPIT Thariq Bin Ziyad</h1>
			</div>
			<div class="col-4">
				<h1 id="edu">education</h1>
			</div>
		</div>
	</div>

	<!-- experiences -->
	<div class="container-fluid" id="experiences">
		<div class="row">
			<div class="col-4">
				<h1 id="ex">experiences</h1>
			</div>
			<div class="card experiences col-8">
				<hr id="ex-line">
				<div class="ex-year">
					<h1 class="year">2018</h1>
				</div>
				<div class="ex1">
					<h1>Open House Fasilkom UI</h1>
					<h5>Staff of Public Relation</h5>
				</div>
				<div class="ex-year">
					<h1 class="year">2019</h1>
				</div>
				<div class="ex2">
					<h1>Wisuda Ganjil Fasilkom UI</h1>
					<h5>Staff of Public Relation</h5>
					<br>
					<h1>COMPFEST 11</h1>
					<h5>Staff of Media Partner</h5>
					<br>
					<h1>DPM Fasilkom UI</h1>
					<h5>Staff of Human Resource Development Division</h5>
					<br>
					<h1>PMB Fasilkom UI</h1>
					<h5>Staff of Medical</h5>
					<br>
					<h1>Wisuda Genap Fasilkom UI</h1>
					<h5>Staff of Liaison Officer</h5>
				</div>
			</div>
		</div>
	</div>

	<!-- contact -->
	<div class="container" id="contact">
		<div class="row">
			<div class="contact-me col" style="color:#fff">
				contact<span style="color:#FF5757">.</span>
			</div>
			<div class="card content col-lg-8 col-sm-12 mx-auto justify-content-center" style="background: #FF5757">
				<div>
					<p class="col-12" id="contact-me" style="color: #000; text-align: center">nabilarizkiandini@gmail.com</p>
					<div class="socmed" style="text-align: center">
						<a href="https://api.whatsapp.com/send?phone=6287884446715" target="_blank"><img style="margin-right:8%" src="{% static 'images/wa.png' %}" alt="whatsapp"></a>
						<a href="https://www.linkedin.com/in/rizkiandini/" target="_blank"><img style="margin-right:8%" src="{% static 'images/in.png' %}" alt="linkedin"></a>
						<a href="https://www.instagram.com/nrizkiandini/" target="_blank"><img style="margin-right:8%" src="{% static 'images/ig.png' %}" alt="instagram"></a>
						<a href="https://line.me/ti/p/x1RvvWy7y4/" target="_blank"><img src="{% static 'images/line.png' %}" alt="line"></a>
					</div>
				</div>
			</div>
			<div class="lets col align-self-end" style="color:#FF5757">
				<span style="color:#fff">let's</span><br>get in touch!
				</p>
			</div>
		</div> 
	</div>
	{% endblock %}
	
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

story4/website/templates/navigation.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Andin</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
	<!-- navigation -->
	<nav class="navbar navbar-expand-md sticky-top">
	  	<button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#main-navigation">
	    	<span class="navbar-toggler-icon"></span>
	  	</button>
	  	<div class="collapse navbar-collapse" id="main-navigation">
	    	<ul class="navbar-nav">
		      	<li class="nav-item">
		        	<a class="nav-link" href="../#home">home</a>
				</li>
		      	<li class="nav-item">
		        	<a class="nav-link" href="../#about">about</a>
				</li>
		      	<li class="nav-item">
		        	<a class="nav-link" href="../#contact">contact</a>
				</li>
				<li class="nav-item">
		        	<a class="nav-link" href="{% url 'website:gallery' %}">gallery</a>
		      	</li>
	    	</ul>
	  	</div>
    </nav>
    {% block content %}{% endblock %}
	
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>